function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------
g = double(im); % Normalized Image % Normalized Image
n = double(im.*2);
c = 0.20; % Constant
l = c*log(1 + (g)); % Log Transform
a= edge(g,'Canny',0.2,3);
b=edge(g,'Canny');


results.l =l;
results.n =n;
results.g =g;
results.a =a;
results.b =b;


%-------------



%--------------------------------------------------------------------------
