function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------

% Replace the sample below with your code----------------------------------
g = double(im); % Normalized Image % Normalized Image
n = double(im.*2);
c = 0.20; % Constant
l = c*log(1 + (g)); % Log Transform
a= edge(n,'Canny',0.15,3);
b=edge(n,'Canny');


results.l =l;
results.n =n;
results.g =g;
results.a =a;
results.b =b;


f1 = imfill(b,'holes');
se = strel('line',11,0);
se0 = strel('line',11,90);

d1 = imdilate(a,[se se0]);
f2 = imfill(d1, 'holes');
e = imerode(f2,[se se0]);

results.d1 =d1;
results.e =e;
results.f2 =f2;
results.f1 =f1;

%-------------



%--------------------------------------------------------------------------
